---
  - debug: var="upstart_config"

  - debug: msg="templating /etc/init/{{upstart_name | default('??')}}.conf from {{role_dir}}/templates/start/upstart.conf.j2 (overrided - {{upstart_template | default('no')}})"

  - name: UPSTART | Template upstart script
    template: src="{{role_dir}}/templates/start/upstart.conf.j2" dest="/etc/init/{{item.name}}.conf"
    become: yes
